@baseURL = http://localhost:3333/api

# @name createTransactions
POST {{baseURL}}/transactions 
Content-Type: application/json 

{
  "amount": 1998,
  "type": "credit"
}

###

# @name listTransactions
GET {{baseURL}}/transactions 
Content-Type: application/json 